// Code generated by goctl. DO NOT EDIT.
// Source: cluster.proto

package server

import (
	"context"

	"cluster/internal/logic"
	"cluster/internal/svc"
	"cluster/types/cluster"
)

type ClusterServer struct {
	svcCtx *svc.ServiceContext
	cluster.UnimplementedClusterServer
}

func NewClusterServer(svcCtx *svc.ServiceContext) *ClusterServer {
	return &ClusterServer{
		svcCtx: svcCtx,
	}
}

func (s *ClusterServer) Cluster(ctx context.Context, in *cluster.ClusterRequest) (*cluster.ClusterResponse, error) {
	l := logic.NewClusterLogic(ctx, s.svcCtx)
	return l.Cluster(in)
}
